repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.8.0
  #   hooks:
  #     - id: markdownlint
